version: '3.8'

services:
  fake-logger:
    build: ./logger
    container_name: fake-logger
    environment:
      - LOG_FILE=/logs/app.log
      - INTERVAL=10
    volumes:
      - fake_logs:/logs
    restart: unless-stopped

  nxlog:
    build: ./nxlog
    container_name: nxlog
    volumes:
      - fake_logs:/logs:ro
      - ./nxlog/nxlog.conf:/etc/nxlog/nxlog.conf:ro
    depends_on:
      - log-target
      - fake-logger
    restart: unless-stopped

  log-target:
    build: ./log-target
    container_name: log-target
    ports:
    - "5140:5140"
    volumes:
      - log_target:/logs
    restart: unless-stopped

volumes:
  fake_logs:
  log_target:
