version: '3.8'

services:
  fake-logger:
    build: ./logger
    container_name: fake-logger
    environment:
      - LOG_FILE=/logs/app.log # fake-logger kirjoittaa tänne
      - INTERVAL=10 # 10 sekunnin kirjoitus viive
    volumes:
      - fake_logs:/logs # nimetty Docker volume /logs-kansiolle
    restart: unless-stopped
  nxlog:
    build: ./nxlog      # käytetään omaa buildia
    container_name: nxlog
    volumes:
      - fake_logs:/logs:ro  # read-only luku fake-loggerin tuotannosta
      - ./nxlog/nxlog.conf:/etc/nxlog/nxlog.conf:ro # NXLog konffit read-only
      - nxlog_out:/nxlog/out # NXLogin keräämät logit talteen tähän volumeen
    depends_on:
      - fake-logger

volumes:
  fake_logs: # tallentaa fake-loggerin logit pysyvästi
  nxlog_out: # tallentaa NXLogin keräämät logit pysyvästi